-- Add 25 new coloring pages with Spanish translations
-- Categories: Basketball Players (8), K Pop Demon Hunters (5), Numbers (11), Mandalas (1)

-- Basketball Players --
INSERT INTO paintings (url_key, title, description, title_es, description_es, category, difficulty, image_url, thumbnail_url, created_at) VALUES
('giannis_antetokounmpo', 'Giannis Antetokounmpo', 'Color Giannis Antetokounmpo, the Greek Freak! Perfect for basketball fans and young athletes.', 'Giannis Antetokounmpo', '¡Colorea a Giannis Antetokounmpo, el Greek Freak! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/giannis_antetokounmpo.png', '/coloring-images/giannis_antetokounmpo.png', CURRENT_TIMESTAMP),
('jayson_tatum', 'Jayson Tatum', 'Color Jayson Tatum, Boston Celtics star! Perfect for basketball fans and young athletes.', 'Jayson Tatum', '¡Colorea a Jayson Tatum, estrella de Boston Celtics! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/jayson_tatum.png', '/coloring-images/jayson_tatum.png', CURRENT_TIMESTAMP),
('kawhi_leonard', 'Kawhi Leonard', 'Color Kawhi Leonard, the Klaw! Perfect for basketball fans and young athletes.', 'Kawhi Leonard', '¡Colorea a Kawhi Leonard, el Klaw! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/kawhi_leonard.png', '/coloring-images/kawhi_leonard.png', CURRENT_TIMESTAMP),
('kevin_durant', 'Kevin Durant', 'Color Kevin Durant, NBA superstar! Perfect for basketball fans and young athletes.', 'Kevin Durant', '¡Colorea a Kevin Durant, superestrella de la NBA! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/kevin_durant.png', '/coloring-images/kevin_durant.png', CURRENT_TIMESTAMP),
('kobe_bryant', 'Kobe Bryant', 'Color Kobe Bryant, the Black Mamba! Perfect for basketball fans and young athletes.', 'Kobe Bryant', '¡Colorea a Kobe Bryant, la Mamba Negra! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/kobe_bryant.png', '/coloring-images/kobe_bryant.png', CURRENT_TIMESTAMP),
('lebron_james', 'LeBron James', 'Color LeBron James, the King! Perfect for basketball fans and young athletes.', 'LeBron James', '¡Colorea a LeBron James, el Rey! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/lebron_james.png', '/coloring-images/lebron_james.png', CURRENT_TIMESTAMP),
('michael_jordan', 'Michael Jordan', 'Color Michael Jordan, basketball legend! Perfect for basketball fans and young athletes.', 'Michael Jordan', '¡Colorea a Michael Jordan, leyenda del baloncesto! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/michael_jordan.png', '/coloring-images/michael_jordan.png', CURRENT_TIMESTAMP),
('stephen_curry', 'Stephen Curry', 'Color Stephen Curry, the three-point king! Perfect for basketball fans and young athletes.', 'Stephen Curry', '¡Colorea a Stephen Curry, el rey de los triples! Perfecto para fanáticos del baloncesto y jóvenes atletas.', 'Basketball Players', 2, '/coloring-images/stephen_curry.png', '/coloring-images/stephen_curry.png', CURRENT_TIMESTAMP);

-- K Pop Demon Hunters --
INSERT INTO paintings (url_key, title, description, title_es, description_es, category, difficulty, image_url, thumbnail_url, created_at) VALUES
('k_pop_demon_hunters', 'K-Pop Demon Hunters', 'Color the K-Pop Demon Hunters team! Perfect for fans of action and music.', 'Cazadores de Demonios K-Pop', '¡Colorea al equipo de Cazadores de Demonios K-Pop! Perfecto para fanáticos de la acción y la música.', 'K Pop Demon Hunters', 3, '/coloring-images/k_pop_demon_hunters.png', '/coloring-images/k_pop_demon_hunters.png', CURRENT_TIMESTAMP),
('mira', 'Mira', 'Color Mira, the fierce demon hunter! Perfect for fans of action heroes.', 'Mira', '¡Colorea a Mira, la feroz cazadora de demonios! Perfecto para fanáticos de héroes de acción.', 'K Pop Demon Hunters', 3, '/coloring-images/mira.png', '/coloring-images/mira.png', CURRENT_TIMESTAMP),
('rumi', 'Rumi', 'Color Rumi, the brave demon hunter! Perfect for fans of action heroes.', 'Rumi', '¡Colorea a Rumi, la valiente cazadora de demonios! Perfecto para fanáticos de héroes de acción.', 'K Pop Demon Hunters', 3, '/coloring-images/rumi.png', '/coloring-images/rumi.png', CURRENT_TIMESTAMP),
('zoey', 'Zoey', 'Color Zoey, the powerful demon hunter! Perfect for fans of action heroes.', 'Zoey', '¡Colorea a Zoey, la poderosa cazadora de demonios! Perfecto para fanáticos de héroes de acción.', 'K Pop Demon Hunters', 3, '/coloring-images/zoey.png', '/coloring-images/zoey.png', CURRENT_TIMESTAMP),
('the_saja_boys', 'The Saja Boys', 'Color the Saja Boys, demon hunting heroes! Perfect for fans of action teams.', 'Los Chicos Saja', '¡Colorea a los Chicos Saja, héroes cazadores de demonios! Perfecto para fanáticos de equipos de acción.', 'K Pop Demon Hunters', 3, '/coloring-images/the_saja_boys.png', '/coloring-images/the_saja_boys.png', CURRENT_TIMESTAMP);

-- Numbers --
INSERT INTO paintings (url_key, title, description, title_es, description_es, category, difficulty, image_url, thumbnail_url, created_at) VALUES
('zero', 'Number Zero', 'Color the number 0! Perfect for learning numbers while having fun.', 'Número Cero', '¡Colorea el número 0! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/zero.png', '/coloring-images/zero.png', CURRENT_TIMESTAMP),
('one', 'Number One', 'Color the number 1! Perfect for learning numbers while having fun.', 'Número Uno', '¡Colorea el número 1! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/one.png', '/coloring-images/one.png', CURRENT_TIMESTAMP),
('two', 'Number Two', 'Color the number 2! Perfect for learning numbers while having fun.', 'Número Dos', '¡Colorea el número 2! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/two.png', '/coloring-images/two.png', CURRENT_TIMESTAMP),
('three', 'Number Three', 'Color the number 3! Perfect for learning numbers while having fun.', 'Número Tres', '¡Colorea el número 3! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/three.png', '/coloring-images/three.png', CURRENT_TIMESTAMP),
('four', 'Number Four', 'Color the number 4! Perfect for learning numbers while having fun.', 'Número Cuatro', '¡Colorea el número 4! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/four.png', '/coloring-images/four.png', CURRENT_TIMESTAMP),
('five', 'Number Five', 'Color the number 5! Perfect for learning numbers while having fun.', 'Número Cinco', '¡Colorea el número 5! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/five.png', '/coloring-images/five.png', CURRENT_TIMESTAMP),
('six', 'Number Six', 'Color the number 6! Perfect for learning numbers while having fun.', 'Número Seis', '¡Colorea el número 6! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/six.png', '/coloring-images/six.png', CURRENT_TIMESTAMP),
('seven', 'Number Seven', 'Color the number 7! Perfect for learning numbers while having fun.', 'Número Siete', '¡Colorea el número 7! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/seven.png', '/coloring-images/seven.png', CURRENT_TIMESTAMP),
('eight', 'Number Eight', 'Color the number 8! Perfect for learning numbers while having fun.', 'Número Ocho', '¡Colorea el número 8! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/eight.png', '/coloring-images/eight.png', CURRENT_TIMESTAMP),
('nine', 'Number Nine', 'Color the number 9! Perfect for learning numbers while having fun.', 'Número Nueve', '¡Colorea el número 9! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/nine.png', '/coloring-images/nine.png', CURRENT_TIMESTAMP),
('ten', 'Number Ten', 'Color the number 10! Perfect for learning numbers while having fun.', 'Número Diez', '¡Colorea el número 10! Perfecto para aprender números mientras te diviertes.', 'Numbers', 1, '/coloring-images/ten.png', '/coloring-images/ten.png', CURRENT_TIMESTAMP);

-- Mandalas --
INSERT INTO paintings (url_key, title, description, title_es, description_es, category, difficulty, image_url, thumbnail_url, created_at) VALUES
('flower_mandala', 'Flower Mandala', 'Color a beautiful flower mandala! Perfect for relaxation and creativity.', 'Mandala de Flores', '¡Colorea un hermoso mandala de flores! Perfecto para relajación y creatividad.', 'Mandalas', 3, '/coloring-images/flower_mandala.png', '/coloring-images/flower_mandala.png', CURRENT_TIMESTAMP);



